dob <- subset_samples(neon_dob, get_variable(neon_dob, "Project")=="DoB")
dob <- subset_samples(dob, !is.na(Site))
dob_o <- subset_samples(dob, horizon == "O")
rm(neon_dob)

d2 <- sample_data(dob_o)

a2 <- unique(d2$Site)# be noted that the resulting site orders may not be identical to that of generated by the 'merge_samples' function you used at line 128
result.c <- matrix(nrow = 42, ncol = 4)
result.z <- matrix(nrow = 42, ncol = 4)
rownames(result.c) <- a2
rownames(result.z) <- a2
for (i in 1:length(a2)){
  # take out one site
  dob_o_sub <- subset_samples(dob_o, Site==a2[i])
  dim1 <- dim(otu_table(dob_o_sub)) # the number of samples in one site
  species <- vector(length = dim1[1]) # create a vector to save diversity
  for (j in 1:(dim1[1])){ 
    
    # randomly sample j samples in the site 
    flag <- rep(FALSE, dim1[1])
    flag[sample(1:dim1[1], j)] <- TRUE
    temp <- merge_samples(dob_o_sub, flag, function(x) mean(x, na.rm = TRUE)) # the j samples aggregated by mean
    
    # compute number of species
    species[j] <- sum(otu_table(temp)["TRUE"] > 0)
  }
  ex <- as.data.frame(cbind(species, "A"=c(1:dim1[1])))
  temp <- summary(nls(species~c*A^z,ex,start = list(c=1,z=1)))[["coefficients"]]
  result.c[i,] <- temp[1,]
  result.z[i,] <- temp[2,]
}
colnames(result.z) <- colnames(summary(nls(species~c*A^z,ex,start = list(c=1,z=1)))[["coefficients"]])
result.z[,4] > 0.05
hist(result.z[,1])
summary(result.z[,1])

# merge samples and linear regression
write.table(result.z,"dob_o.z.txt")
write.table(result.c,"dob_o.c.txt")
# merge samples and linear regression
# dob_o_site <- merge_samples(dob_o, "Site")
#d_site <- sample_data(dob_o_site)

d2$map_mm[is.nan(d2$map_mm)] = NA
d_site <- sample_data(dob_o)
d_site <- aggregate(cbind(d_site$soilInCaClpH,d_site$nitrogenPercent,d_site$organicCPercent,
                          d_site$soilMoisture, d_site$map_mm,d_site$prec_seasonality,d_site$mat_celsius,
                          d_site$temp_seasonality),list(d_site$Site), function(x) mean(x,na.rm = T))
d_site$V2[is.nan(d_site$V2)] = NA
d_site$V3[is.nan(d_site$V3)] = NA
d_site$V4[is.nan(d_site$V4)] = NA
row.names(d_site) <- d_site$Group.1
#d_site <- data.frame(scale(d_site[,-1]))
d_site <- d_site[,-1]
colnames(d_site) <- c("soilInCaClpH","nitrogenPercent","organicCPercent",
                      "soilMoisture", "map_mm",'prec_seasonality',"mat_celsius",
                      "temp_seasonality")
# standardization seems to have no effect on significance
d_site <- d_site[a2,]
summary(lm(result.z[,1] ~ d_site$soilInCaClpH + d_site$soilMoisture + d_site$mat_celsius +
             d_site$map_mm + d_site$temp_seasonality + d_site$prec_seasonality))

# data with no missing values
summary(lm(scale(result.z[,1]) ~ d_site$mat_celsius +
             d_site$map_mm + d_site$temp_seasonality + d_site$prec_seasonality))

summary(lm(result.z[,1] ~ d_site$mat_celsius +
             d_site$map_mm + d_site$temp_seasonality + d_site$prec_seasonality))

p1 <- ggtrendline(d_site$soilInCaClpH, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$soilInCaClpH, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("soilInCaClpH")+ylab("z")

p2 <- ggtrendline(d_site$soilMoisture, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$soilMoisture, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("soilMoisture")+ylab("z")

p3 <- ggtrendline(d_site$mat_celsius, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$mat_celsius, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("mat_celsius")+ylab("z")

p4 <- ggtrendline(d_site$map_mm, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$map_mm, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("map_mm")+ylab("z")

p5 <- ggtrendline(d_site$temp_seasonality, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$temp_seasonality, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("temp_seasonality")+ylab("z") 

p6 <- ggtrendline(d_site$prec_seasonality, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$prec_seasonality, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("prec_seasonality")+ylab("z") 

grid.arrange(p1,p2,p3,p4,p5,p6,ncol = 3)

# M horizon
dob_m <- subset_samples(dob, horizon == "M")
rm(neon_dob)
d_site <- sample_data(dob_m)
a2 <- unique(d_site$Site)# be noted that the resulting site orders may not be identical to that of generated by the 'merge_samples' function you used at line 128
result.c <- matrix(nrow = 43, ncol = 4)
result.z <- matrix(nrow = 43, ncol = 4)
rownames(result.c) <- a2
rownames(result.z) <- a2
for (i in 1:length(a2)){
  # take out one site
  dob_m_sub <- subset_samples(dob_m, Site==a2[i])
  dim1 <- dim(otu_table(dob_m_sub)) # the number of samples in one site
  species <- vector(length = dim1[1]) # create a vector to save diversity
  for (j in 1:(dim1[1])){ 
    
    # randomly sample j samples in the site 
    flag <- rep(FALSE, dim1[1])
    flag[sample(1:dim1[1], j)] <- TRUE
    temp <- merge_samples(dob_m_sub, flag, function(x) mean(x, na.rm = TRUE)) # the j samples aggregated by mean
    
    # compute number of species
    species[j] <- sum(otu_table(temp)["TRUE"] > 0)
  }
  ex <- as.data.frame(cbind(species, "A"=c(1:dim1[1])))
  temp <- summary(nls(species~c*A^z,ex,start = list(c=1,z=1)))[["coefficients"]]
  result.c[i,] <- temp[1,]
  result.z[i,] <- temp[2,]
}
colnames(result.z) <- colnames(summary(nls(species~c*A^z,ex,start = list(c=1,z=1)))[["coefficients"]])
result.z[,4] > 0.05
hist(result.z[,1])
summary(result.z[,1])

# merge samples and linear regression
write.table(result.z,"dob_m.z.txt")
write.table(result.c,"dob_m.c.txt")
# merge samples and linear regression
# dob_m_site <- merge_samples(dob_m, "Site")
#d_site <- sample_data(dob_m_site)
d_site <- sample_data(dob_m)
d_site$nitrogenPercent[is.nan(d_site$nitrogenPercent)] = NA
d_site$organicCPercent[is.nan(d_site$organicCPercent)] = NA
d_site$map_mm[is.nan(d_site$map_mm)] = NA

d_site <- aggregate(cbind(d_site$soilInCaClpH,d_site$nitrogenPercent,d_site$organicCPercent,
                          d_site$soilMoisture, d_site$map_mm,d_site$prec_seasonality,d_site$mat_celsius,
                          d_site$temp_seasonality),list(d_site$Site), function(x) mean(x,na.rm = T))
d_site$V2[is.nan(d_site$V2)] = NA
d_site$V3[is.nan(d_site$V3)] = NA
d_site$V4[is.nan(d_site$V4)] = NA
row.names(d_site) <- d_site$Group.1
# d_site <- data.frame(scale(d_site[,-1]))
d_site <- d_site[,-1]
colnames(d_site) <- c("soilInCaClpH","nitrogenPercent","organicCPercent",
                      "soilMoisture", "map_mm",'prec_seasonality',"mat_celsius",
                      "temp_seasonality")
# standardization seems to have no effect on significance
d_site <- d_site[a2,]
summary(lm(result.z[,1] ~ d_site$soilInCaClpH + d_site$soilMoisture + d_site$mat_celsius +
             d_site$map_mm + d_site$temp_seasonality + d_site$prec_seasonality))

# data with no missing values
summary(lm(scale(result.z[,1]) ~ d_site$mat_celsius +
             d_site$map_mm + d_site$temp_seasonality + d_site$prec_seasonality))

summary(lm(result.z[,1] ~ d_site$mat_celsius +
             d_site$map_mm + d_site$temp_seasonality + d_site$prec_seasonality))

p1 <- ggtrendline(d_site$soilInCaClpH, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$soilInCaClpH, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("soilInCaClpH")+ylab("z")

p2 <- ggtrendline(d_site$soilMoisture, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$soilMoisture, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("soilMoisture")+ylab("z")

p3 <- ggtrendline(d_site$mat_celsius, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$mat_celsius, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("mat_celsius")+ylab("z")

p4 <- ggtrendline(d_site$map_mm, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$map_mm, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("map_mm")+ylab("z")

p5 <- ggtrendline(d_site$temp_seasonality, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$temp_seasonality, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("temp_seasonality")+ylab("z") 

p6 <- ggtrendline(d_site$prec_seasonality, result.z[,1],linecolor="red")+
  geom_point(aes(d_site$prec_seasonality, result.z[,1]),color="black",pch=21,fill='white')+
  xlab("prec_seasonality")+ylab("z") 

grid.arrange(p1,p2,p3,p4,p5,p6,ncol = 3)

